---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Check whether required packages are installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      loop: "{{ base_packages }}"

    - name: Check whether required pip package are reporting version
      command: "{{ item.split('=')|first }} --version"
      register: result
      failed_when: result.rc > 0
      changed_when: false
      loop: "{{ base_pip_packages }}"
